# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('qrcodeContent', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('vehicleNumber', models.CharField(blank=True, max_length=100)),
                ('username', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='oAuth.User')),
            ],
        ),
    ]
