# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='time',
            field=models.TimeField(),
        ),
    ]
