# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170630_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='Place_to_visit',
            field=models.CharField(default='Bharti Building', max_length=100),
            preserve_default=False,
        ),
    ]
