# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_qrcode_place_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qrcodeContent',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
