# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170702_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='vehicleStatus',
            field=models.CharField(choices=[('AC', 'Active'), ('GP', 'Entered Campus'), ('PA', 'Vehicle Parked'), ('EX', 'Exited Campus'), ('IN', 'Inactive')], default='AC', max_length=2),
        ),
    ]
