# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_auto_20170630_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('AD', 'admin'), ('CL', 'client')], default='CL', max_length=2),
        ),
    ]
